name: la-plume

services:
  web:
    build: .
    image: la-plume-web:dev
    env_file: .env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - mongo
      - mailpit
    volumes:
      - .:/app

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_NAME:-db_psql_labrary}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodata:/data/db

  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "1025:1025"   # SMTP
      - "8025:8025"   # UI web

volumes:
  pgdata:
  mongodata:
