"""Fix CartItem and Book relationship

Revision ID: 0ca9c5c8e03f
Revises: 892d5d05e3ca
Create Date: 2024-11-24 13:28:45.638638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca9c5c8e03f'
down_revision = '892d5d05e3ca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('Orders')
    # op.drop_table('order_details')
    # op.drop_table('books')
    # ### end Alembic commands ###
    pass

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_table('order_details',
    sa.Column('order_details_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name='order_details_book_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name='order_details_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_details_id', name='order_details_pkey')
    )
    op.create_table('Orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey')
    )
    # ### end Alembic commands ###
