"""Ajout du champ user_signup_date au modèle User

Revision ID: 2f55239f8c93
Revises: 9662f90783c2
Create Date: 2024-11-24 16:41:00.683314

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f55239f8c93'
down_revision = '9662f90783c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_table('books')
    # op.drop_table('Orders')
    # op.drop_table('order_details')
    # with op.batch_alter_table('User', schema=None) as batch_op:
    #     batch_op.alter_column('user_signup_date',
    #            existing_type=sa.DATE(),
    #            type_=sa.DateTime(),
    #            nullable=False)
    #     batch_op.drop_column('user_phone')
    pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.alter_column('user_signup_date',
               existing_type=sa.DateTime(),
               type_=sa.DATE(),
               nullable=True)

    op.create_table('order_details',
    sa.Column('order_details_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name='order_details_book_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name='order_details_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_details_id', name='order_details_pkey')
    )
    op.create_table('Orders',
    sa.Column('order_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey')
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    # ### end Alembic commands ###
