"""Ajout du champ user_role

Revision ID: 3b361a002e1a
Revises: ea7760cae50b
Create Date: 2025-03-29 18:28:35.050622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3b361a002e1a'
down_revision = 'ea7760cae50b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_role', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('user_role')

    # ### end Alembic commands ###
