"""Fix cart_items relationship conflict

Revision ID: 9662f90783c2
Revises: d9975eb97b40
Create Date: 2024-11-24 14:03:21.779718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9662f90783c2'
down_revision = 'd9975eb97b40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted to prevent dropping columns/tables ###

    # Suppression des lignes suivantes pour ne pas supprimer les tables ou colonnes
    # op.drop_table('order_details')
    # op.drop_table('books')
    # op.drop_table('Orders')

    # Suppression des lignes pour ne pas supprimer de colonnes dans la table 'User'
    # with op.batch_alter_table('User', schema=None) as batch_op:
    #     batch_op.drop_column('user_signup_date')
    #     batch_op.drop_column('user_phone')

    pass  # Ajout d'un pass pour indiquer que la migration ne fait rien ici


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.VARCHAR(length=15), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('user_signup_date', sa.DATE(), autoincrement=False, nullable=True))

    op.create_table('Orders',
    sa.Column('order_id', sa.INTEGER(), server_default=sa.text("nextval('orders_order_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('order_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=50), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['User.user_id'], name='orders_user_id_fkey'),
    sa.PrimaryKeyConstraint('order_id', name='orders_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('books',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('author', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='books_pkey')
    )
    op.create_table('order_details',
    sa.Column('order_details_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('book_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('unit_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['Book.book_id'], name='order_details_book_id_fkey'),
    sa.ForeignKeyConstraint(['order_id'], ['Orders.order_id'], name='order_details_order_id_fkey'),
    sa.PrimaryKeyConstraint('order_details_id', name='order_details_pkey')
    )
    # ### end Alembic commands ###
