"""add security fields

Revision ID: ef30efc16c05
Revises: ede907d3d316
Create Date: 2025-04-15 20:38:26.731587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef30efc16c05'
down_revision = 'ede907d3d316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('last_failed_login', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('account_locked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('account_locked')
        batch_op.drop_column('last_failed_login')
        batch_op.drop_column('failed_login_attempts')

    # ### end Alembic commands ###
